//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParkingData
{
    using Dapper.Contrib.Extensions;
    using System;
    using System.Collections.Generic;

    public partial class BuildingClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildingClass()
        {
            this.BuildingPark = new HashSet<BuildingPark>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> BuildingClassMasterId { get; set; }
        [Write(false)]
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Write(false)]
        public virtual ICollection<BuildingPark> BuildingPark { get; set; }
        [Write(false)]
        public virtual BuildingClassMaster BuildingClassMaster { get; set; }
    }
}
