//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParkingData
{
    using Dapper.Contrib.Extensions;
    using System;
    using System.Collections.Generic;

    public partial class BuildingPark
    {
        public int Id { get; set; }
        public Nullable<int> BuildingClassId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> BuildingParkMasterId { get; set; }
        [Write(false)]
        public virtual BuildingClass BuildingClass { get; set; }
        [Write(false)]
        public virtual BuildingClassMaster BuildingClassMaster { get; set; }
        [Write(false)]
        public virtual BuildingParkMaster BuildingParkMaster { get; set; }
    }
}
