//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParkingData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingDBEntities : DbContext
    {
        public ParkingDBEntities()
            : base("name=ParkingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<BuildingClass> BuildingClass { get; set; }
        public virtual DbSet<BuildingPark> BuildingPark { get; set; }
        public virtual DbSet<General> General { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<RfidStamp> RfidStamp { get; set; }
        public virtual DbSet<BuildingClassMaster> BuildingClassMaster { get; set; }
        public virtual DbSet<BuildingParkMaster> BuildingParkMaster { get; set; }
        public virtual DbSet<RfidConfig> RfidConfig { get; set; }
    }
}
